// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               v5.28.2
// source: order.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "order";

export interface CreateOrderDto {
  amount: number;
  userId: number;
  orderStatusId: number;
  orderItems: CreateOrderItemWithOrderDto[];
}

export interface Order {
  id: number;
  amount: number;
  userId: number;
  orderStatusId: number;
  createdAt: string;
  updatedAt: string;
}

export interface Orders {
  orders: Order[];
}

export interface Empty {
}

export interface UpdateOrderDto {
  id: number;
  amount: number;
  orderStatusId: number;
}

export interface DeleteOrderDto {
  id: number;
}

export interface DeleteOrderResponse {
  orderStatusId: number;
  error: string[];
}

export interface FindOneOrderDto {
  id: number;
}

export interface PaginationDto {
  page: number;
  skip: number;
}

export interface CreateOrderItemDto {
  amount: number;
  orderId: number;
  serviceName: string;
}

export interface CreateOrderItemsDto {
  createOrderItemsDto: CreateOrderItemDto[];
}

export interface OrderItem {
  id: number;
  amount: number;
  orderId: number;
  serviceName: string;
  createdAt: string;
  updatedAt: string;
}

export interface OrderItems {
  orderItems: OrderItem[];
}

export interface UpdateOrderItemDto {
  amount: number;
  orderId: number;
  serviceName: string;
}

export interface DeleteOrderItemDto {
  id: number;
}

export interface DeleteOrderItemResponse {
  orderStatusId: number;
  error: string[];
}

export interface CreateOrderItemWithOrderDto {
  amount: number;
  serviceName: string;
}

export const ORDER_PACKAGE_NAME = "order";

export interface OrderServiceClient {
  createOrder(request: CreateOrderDto): Observable<Order>;

  findOneOrder(request: FindOneOrderDto): Observable<Order>;

  findAllOrder(request: Empty): Observable<Orders>;

  updateOrder(request: UpdateOrderDto): Observable<Order>;

  deleteOrder(request: DeleteOrderDto): Observable<DeleteOrderResponse>;

  queryOrders(request: Observable<PaginationDto>): Observable<Orders>;
}

export interface OrderServiceController {
  createOrder(request: CreateOrderDto): Promise<Order> | Observable<Order> | Order;

  findOneOrder(request: FindOneOrderDto): Promise<Order> | Observable<Order> | Order;

  findAllOrder(request: Empty): Promise<Orders> | Observable<Orders> | Orders;

  updateOrder(request: UpdateOrderDto): Promise<Order> | Observable<Order> | Order;

  deleteOrder(
    request: DeleteOrderDto,
  ): Promise<DeleteOrderResponse> | Observable<DeleteOrderResponse> | DeleteOrderResponse;

  queryOrders(request: Observable<PaginationDto>): Observable<Orders>;
}

export function OrderServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createOrder", "findOneOrder", "findAllOrder", "updateOrder", "deleteOrder"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = ["queryOrders"];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ORDER_SERVICE_NAME = "OrderService";

export interface OrderItemServiceClient {
  createOrderItem(request: CreateOrderItemDto): Observable<OrderItem>;

  updateOrderItem(request: UpdateOrderItemDto): Observable<OrderItem>;

  deleteOrderItem(request: DeleteOrderItemDto): Observable<DeleteOrderItemResponse>;
}

export interface OrderItemServiceController {
  createOrderItem(request: CreateOrderItemDto): Promise<OrderItem> | Observable<OrderItem> | OrderItem;

  updateOrderItem(request: UpdateOrderItemDto): Promise<OrderItem> | Observable<OrderItem> | OrderItem;

  deleteOrderItem(
    request: DeleteOrderItemDto,
  ): Promise<DeleteOrderItemResponse> | Observable<DeleteOrderItemResponse> | DeleteOrderItemResponse;
}

export function OrderItemServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createOrderItem", "updateOrderItem", "deleteOrderItem"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("OrderItemService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("OrderItemService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ORDER_ITEM_SERVICE_NAME = "OrderItemService";
